# Generated by Django 4.2 on 2023-05-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(unique=True)),
                ('sortCode', models.TextField(blank=True, verbose_name='SortCode')),
                ('nameOnAccount', models.TextField(blank=True, verbose_name='Name on Account')),
            ],
        ),
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_ID', models.TextField(blank=True, unique=True, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueBankAccID', models.TextField(blank=True, verbose_name='IssueBankAccID')),
                ('acqBankAccID', models.TextField(blank=True, verbose_name='AcqBankAccID')),
                ('amount', models.FloatField()),
                ('currencyCode', models.PositiveIntegerField()),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit_transactions.uuid')),
            ],
        ),
    ]
